// Catalogue follows docs/fleet-spec.md. Null means unknown, never an inferred specification.
export const catalogSource = {
  title: "太空舰队-型号舷号与编成规范.md",
  version: "草案 A",
  date: "2026-09-19",
  sourceSha256:
    "130ff98e09c7c530ec45d2ccf24e8590dfe552d8eab803027d6cd2cd77ee376c",
  sha256: "388c62a6da8530ad3cd5a0c785a65353fff8c1ba0e4bbd850be36310183fb26a",
};

export const series = [
  {
    code: "HT",
    name: "远征母舰",
    role: "EXPEDITIONARY CARRIER",
    group: "主战与区控",
    numberRange: "1xxx",
    mission: "可机动的轨道前进基地：机群、C2、推进剂与弹药中转。",
    formation: "编队几何中心或阴影侧，回收窗口由 XJ、QS 与 HW 保护。",
    optional: false,
  },
  {
    code: "ZJ",
    name: "破轨主力舰",
    role: "ORBITAL BREACH CAPITAL SHIP",
    group: "主战与区控",
    numberRange: "4xxx",
    mission: "在交会窗口内打击加固目标、要塞与大型空间站。",
    formation: "突击段压上，完成打击后立即改轨脱离。",
    optional: false,
  },
  {
    code: "XJ",
    name: "区控巡洋舰",
    role: "AREA CONTROL CRUISER",
    group: "主战与区控",
    numberRange: "3xxx",
    mission: "远程传感、多层拦截与支队指挥。",
    formation: "传感前出与拦截走廊中段；无 HT 时可任支队旗核。",
    optional: false,
  },
  {
    code: "QS",
    name: "多用途驱逐舰",
    role: "MULTIROLE DESTROYER",
    group: "主战与区控",
    numberRange: "3xxx / 2xxx¹",
    mission: "护航、驱离轻型威胁、局部制轨与编队补位。",
    formation: "数量型主力，分布于护航走廊与拦截幕。",
    optional: false,
  },
  {
    code: "HW",
    name: "护卫舰",
    role: "ESCORT FRIGATE",
    group: "主战与区控",
    numberRange: "2xxx",
    mission: "内圈末段拦截、港站与勤务轨道安全、低烈度巡逻。",
    formation: "运输队与旗核内圈；中型护卫可伴随战斗编队外圈。",
    optional: false,
  },
  {
    code: "QX",
    name: "隐身潜航舰",
    role: "LOW OBSERVABLE INFILTRATOR",
    group: "主战与区控",
    numberRange: "4xxx",
    mission: "低可探测渗透、伏击与破交。",
    formation: "可选任务线，详细条令待定。",
    optional: true,
  },
  {
    code: "YT",
    name: "攻舰快艇级",
    role: "FAST ATTACK CRAFT",
    group: "主战与区控",
    numberRange: null,
    mission: "高机动、短窗口突击。",
    formation: "可选任务线，详细条令与舷号段待定。",
    optional: true,
  },
  {
    code: "YJ",
    name: "预警指挥舰",
    role: "EARLY WARNING & COMMAND",
    group: "体系与支援",
    numberRange: "8xxx",
    mission: "战略级传感与航迹融合。",
    formation: "提供战略传感与告警，不替代 XJ 的编队拦截。",
    optional: false,
  },
  {
    code: "DZ",
    name: "电子战舰",
    role: "ELECTRONIC WARFARE",
    group: "体系与支援",
    numberRange: "8xxx",
    mission: "电磁与频谱对抗、致盲与诱骗。",
    formation: "按任务编配，具体编成待定。",
    optional: false,
  },
  {
    code: "ZX",
    name: "侦察监视舰",
    role: "RECONNAISSANCE & SURVEILLANCE",
    group: "体系与支援",
    numberRange: "8xxx",
    mission: "长期值守与战略侦察。",
    formation: "提供战略传感与航迹信息。",
    optional: false,
  },
  {
    code: "YS",
    name: "运输舰",
    role: "ORBITAL TRANSPORT",
    group: "体系与支援",
    numberRange: "5xxx",
    mission: "人员与物资轨道投送，包含短程穿梭与舰站接驳。",
    formation: "伴飞保障；交战前与旗核拉开安全距离。",
    optional: false,
  },
  {
    code: "BY",
    name: "补给舰",
    role: "FLEET REPLENISHMENT",
    group: "体系与支援",
    numberRange: "6xxx",
    mission: "推进剂、弹药与耗材在轨补给。",
    formation: "维持编队 Δv 与弹仓，远征所必需。",
    optional: false,
  },
  {
    code: "WX",
    name: "维修工程舰",
    role: "REPAIR & ENGINEERING",
    group: "体系与支援",
    numberRange: "6xxx",
    mission: "抢修、拖带与结构作业。",
    formation: "按任务挂靠，不进入标准打击群最小集。",
    optional: false,
  },
  {
    code: "LZ",
    name: "两栖投送舰",
    role: "SURFACE & FACILITY INSERTION",
    group: "体系与支援",
    numberRange: "7xxx",
    mission: "面向表面或设施的投送与回收。",
    formation: "按任务编配，具体编成待定。",
    optional: false,
  },
  {
    code: "JY",
    name: "救援舰",
    role: "SEARCH & RESCUE",
    group: "体系与支援",
    numberRange: "7xxx",
    mission: "搜救与乘员回收。",
    formation: "按任务挂靠，不进入标准打击群最小集。",
    optional: false,
  },
  {
    code: "JL",
    name: "教练舰",
    role: "TRAINING & QUALIFICATION",
    group: "体系与支援",
    numberRange: "9xxx",
    mission: "训练与科目鉴定。",
    formation: "具体训练编成待定。",
    optional: false,
  },
  {
    code: "KY",
    name: "科研试验舰",
    role: "RESEARCH & EXPERIMENTAL",
    group: "体系与支援",
    numberRange: "9xxx",
    mission: "勘探、试验与验证。",
    formation: "按科研与试验任务编配。",
    optional: false,
  },
];

export const fleet = [
  {
    id: "ht-01",
    model: "HT-01A",
    series: "HT",
    name: "标准远征母舰",
    role: "EXPEDITIONARY CARRIER",
    sizeClass: "超",
    status: "规划中",
    state: "planned",
    number: null,
    description: "机群、前进基地与中枢 C2。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "ht-02",
    model: "HT-02A",
    series: "HT",
    name: "轻型前进基地",
    role: "EXPEDITIONARY CARRIER",
    sizeClass: "大",
    status: "可选方案",
    state: "planned",
    number: null,
    description: "少机群、高机动，伴随快速支队。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "zj-01",
    model: "ZJ-01A",
    series: "ZJ",
    name: "重破轨主力舰",
    role: "ORBITAL BREACH CAPITAL SHIP",
    sizeClass: "超",
    status: "规划中",
    state: "planned",
    number: null,
    description: "高毁伤能力，承受第一波反击。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "zj-02",
    model: "ZJ-02A",
    series: "ZJ",
    name: "高机动突击舰",
    role: "ORBITAL BREACH CAPITAL SHIP",
    sizeClass: "超",
    status: "可选方案",
    state: "planned",
    number: null,
    description: "以防护换取 Δv，面向高机动突击。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "xj-01",
    model: "XJ-01A",
    series: "XJ",
    name: "传感拦截型巡洋舰",
    role: "AREA CONTROL CRUISER",
    sizeClass: "大",
    status: "优先规划",
    state: "planned",
    number: null,
    description: "远程传感、多层拦截与支队 C2。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "xj-02",
    model: "XJ-02A",
    series: "XJ",
    name: "远程打击型巡洋舰",
    role: "AREA CONTROL CRUISER",
    sizeClass: "大",
    status: "规划中",
    state: "planned",
    number: null,
    description: "同平台，武备侧重对舰与对设施打击。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "qs-01",
    model: "QS-01A",
    series: "QS",
    name: "通用多用途驱逐舰",
    role: "MULTIROLE DESTROYER",
    sizeClass: "中",
    status: "优先规划",
    state: "planned",
    number: null,
    description: "护航、驱离与局部制轨。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "qs-02",
    model: "QS-02A",
    series: "QS",
    name: "拦截强化型驱逐舰",
    role: "MULTIROLE DESTROYER",
    sizeClass: "中",
    status: "规划中",
    state: "planned",
    number: null,
    description: "同平台，强化拦截能力。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "qs-03",
    model: "QS-03A",
    series: "QS",
    name: "攻舰强化型驱逐舰",
    role: "MULTIROLE DESTROYER",
    sizeClass: "中",
    status: "规划中",
    state: "planned",
    number: null,
    description: "同平台，强化攻舰与反设施能力。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "hw-01",
    model: "HW-01A",
    series: "HW",
    name: "小型护卫舰",
    role: "DEEP SPACE FRIGATE",
    sizeClass: "小",
    status: "设计定型",
    state: "ready",
    number: "2227",
    description: "港站、近地勤务轨道与运输队末段近防。",
    dimensions: [
      ["舰长", "61.1", "M"],
      ["舰宽", "43.6", "M"],
      ["舰高", "23.9", "M"],
    ],
    specs: [
      ["主／副推进器", "2 + 2 台"],
      ["姿态喷口", "24 个 / 六向"],
      ["武器系统", "14 座"],
    ],
    features: [
      [
        "01",
        "四引擎推进架构",
        "两台琥珀色主引擎与两台青蓝色腹部副引擎。承力鞍座、冷却管路与开放喷口，共同定义舰体的机械骨架。",
      ],
      [
        "02",
        "双向曲面控制舱",
        "首尾玻璃舱由金属框架包覆，透过曲面玻璃可见控制台、操作席、仪表架与舱内管路。",
      ],
      [
        "03",
        "分布式防御系统",
        "主炮、近防炮、发射舱与外挑侧炮沿舰体布置，装甲分块与检修通道清晰可辨。",
      ],
    ],
    asset: {
      model: "HW-01",
      number: "227",
    },
  },
  {
    id: "hw-02",
    model: "HW-02A",
    series: "HW",
    name: "中型护卫舰",
    role: "ESCORT FRIGATE",
    sizeClass: "中",
    status: "规划中",
    state: "planned",
    number: null,
    description: "伴随战斗编队外圈，减轻 QS 的近防负担。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "qx",
    model: null,
    series: "QX",
    name: "隐身潜航舰",
    role: "LOW OBSERVABLE INFILTRATOR",
    sizeClass: null,
    status: "可选系列",
    state: "planned",
    number: null,
    description: "低可探测渗透、伏击与破交。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "yt",
    model: null,
    series: "YT",
    name: "攻舰快艇级",
    role: "FAST ATTACK CRAFT",
    sizeClass: null,
    status: "可选系列",
    state: "planned",
    number: null,
    description: "高机动、短窗口突击。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "yj",
    model: null,
    series: "YJ",
    name: "预警指挥舰",
    role: "EARLY WARNING & COMMAND",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "战略级传感与航迹融合。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "dz",
    model: null,
    series: "DZ",
    name: "电子战舰",
    role: "ELECTRONIC WARFARE",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "电磁与频谱对抗、致盲与诱骗。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "zx",
    model: null,
    series: "ZX",
    name: "侦察监视舰",
    role: "RECONNAISSANCE & SURVEILLANCE",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "长期值守与战略侦察。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "ys-01",
    model: "YS-01A",
    series: "YS",
    name: "超小型人员穿梭舰",
    role: "PERSONNEL SHUTTLE",
    sizeClass: "微 / 小",
    status: "原型制作中",
    state: "development",
    number: "5001",
    description: "短程人员与轻货驳运、舰站接驳。",
    dimensions: [
      ["设计舰长", "≈16", "M"],
      ["驾驶席", "02", "席"],
      ["乘员席", "06", "席"],
    ],
    specs: [
      ["任务定位", "人员接驳"],
      ["客舱布局", "3 排 × 2 席"],
      ["固定武器", "无"],
    ],
    features: [
      [
        "01",
        "紧凑一体压力舱",
        "低位全景驾驶窗与三排双座客舱组成连续的人员空间，短推进舱嵌入后肩。",
      ],
      [
        "02",
        "双侧气闸与尾部对接",
        "左右气闸与尾部对接舱适配不同接驳方向，底部设置收拢式起落支撑。",
      ],
      [
        "03",
        "运输家族识别",
        "并行赭黄识别轨、青色灯带和分瓣推进环，延续 YS 系列的民用运输语言。",
      ],
    ],
    asset: {
      model: "YS-01",
      number: "5001",
    },
  },
  {
    id: "ys-02",
    model: "YS-02A",
    series: "YS",
    name: "客货两用运输舰",
    role: "MULTIROLE TRANSPORT",
    sizeClass: "中",
    status: "原型制作中",
    state: "development",
    number: "5002",
    description: "编队伴随与航线物资、人员运输。",
    dimensions: [
      ["设计舰长", "≈30", "M"],
      ["驾驶席", "02", "席"],
      ["乘员席", "12", "席"],
    ],
    specs: [
      ["载运构型", "双层客货舱"],
      ["标准货箱", "4 组"],
      ["自卫近防炮", "1 座"],
    ],
    features: [
      [
        "01",
        "双层客货布局",
        "上层六排双座客舱；下层配置通长货运地板、四个货箱、导轨与系留点。",
      ],
      [
        "02",
        "轴向装卸通道",
        "双侧主推进舱通过斜撑和后部隔舱承力，为尾部货门保留中轴净空。",
      ],
      [
        "03",
        "远途自卫能力",
        "一座近防炮位于上层尾部，远离客舱与装卸路径，保持运输任务优先。",
      ],
    ],
    asset: {
      model: "YS-02",
      number: "5002",
    },
  },
  {
    id: "ys-03",
    model: "YS-03A",
    series: "YS",
    name: "重型舰队运输舰",
    role: "ORBITAL TRANSPORT",
    sizeClass: "大",
    status: "规划中",
    state: "planned",
    number: null,
    description: "大宗运输与远征投送。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "by-01",
    model: "BY-01A",
    series: "BY",
    name: "补给舰",
    role: "FLEET REPLENISHMENT",
    sizeClass: null,
    status: "并行规划",
    state: "planned",
    number: null,
    description: "补给系列首型，与 HW-02A 并行补齐。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "wx",
    model: null,
    series: "WX",
    name: "维修工程舰",
    role: "REPAIR & ENGINEERING",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "抢修、拖带与结构作业。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "lz",
    model: null,
    series: "LZ",
    name: "两栖投送舰",
    role: "SURFACE & FACILITY INSERTION",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "面向表面或设施的投送与回收。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "jy",
    model: null,
    series: "JY",
    name: "救援舰",
    role: "SEARCH & RESCUE",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "搜救与乘员回收。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "jl",
    model: null,
    series: "JL",
    name: "教练舰",
    role: "TRAINING & QUALIFICATION",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "训练与科目鉴定。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
  {
    id: "ky",
    model: null,
    series: "KY",
    name: "科研试验舰",
    role: "RESEARCH & EXPERIMENTAL",
    sizeClass: null,
    status: "系列预留",
    state: "planned",
    number: null,
    description: "勘探、试验与验证。",
    dimensions: null,
    specs: [],
    features: [],
    asset: null,
  },
];

export const viewLabels = {
  "three-quarter": ["三分之四", "PERSPECTIVE"],
  front: ["前视图", "FRONT"],
  rear: ["后视图", "REAR"],
  port: ["左舷视图", "PORT"],
  starboard: ["右舷视图", "STARBOARD"],
  top: ["顶视图", "DORSAL"],
  bottom: ["底视图", "VENTRAL"],
};
